# page properties
name: bryan chacosky
title: bryanchacosky.github.io
description: bryanchacosky.github.io
url: https://bryanchacosky.github.io

# social metadata
email: bryanchacosky@gmail.com
github: https://github.com/bryanchacosky
linkedin: https://www.linkedin.com/in/bryanchacosky/
